version: '3.9'
services:
  customer-service:
    image: customer_image
    container_name: customer-service
    build: bej_c2_s4_rest_api_mongodb_junit_mc_1-master/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8087:8087
    depends_on:
      - mongoService
      - cloudapiservice


  mongoService:
    image: mongo
    container_name: mongoService
    ports:
      - 27017:27017
    networks:
      - mynetwork


  UserAuthenticate :
    image: authentication_image
    container_name: authentication-service
    build: userauthentication-demo-by-mam-master/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8081:8081
    depends_on:
      - mysqlService
      - cloudapiservice

  mysqlService:
    image: mysql:latest
    container_name: mysqlService
    networks:
      - mynetwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  cloudapiservice:
    container_name: cloudapi
    build: springAPIGateWay/
    restart: always
    networks:
      - mynetwork
    ports:
      - 9005:9005

  eureka-service:
    container_name: containerEureka
    build: Eureka_server_Challenge/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8761:8761


networks:
  mynetwork:
    driver: bridge