FROM openjdk
WORKDIR usr/lib
ADD ./target/Eureka_server_Challenge-0.0.1-SNAPSHOT.jar /usr/lib/Eureka_server_Challenge-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","Eureka_server_Challenge-0.0.1-SNAPSHOT.jar"]